### ISSUE TITLE
fail to launch stanley_controlller.launch

### ISSUE THREAD

**Issue by YeanZeeon** [Raiden49/stanley_controller#1]
that really disappoints me

**Comment by Raiden49** [comment]
Could you please let me take a look at the error message?

**Comment by YeanZeeon** [comment]
![image](https://github.com/Raiden49/stanley_controller/assets/147539286/40c196c6-37e0-4aae-b954-6bd48a05a89f)
it shows like this. i am so appreciated that you can help

**Comment by Raiden49** [comment]
You're welcome, I'm also glad to be able to help you. Before running, do you execute this step? source ./build/devel/setup.bash

**Comment by Raiden49** [comment]
If you do have completed that step, have the folder permissions been granted? sudo chmod 777 stanley_controller

**Comment by YeanZeeon** [comment]
![image](https://github.com/Raiden49/stanley_controller/assets/147539286/87fe985c-de90-4c8f-8741-d20832f70aa9)
sad, the same

**Comment by Raiden49** [comment]
1.catkin_find --without-underlays --libexec --share stanley_controller_node
2.cd src/stanley_controller
3.source ./build/devel/setup.bash
4.catkin_find --without-underlays --libexec --share stanley_controller_node
Check if there's only one package path in the results for steps 1 and 4.

**Comment by Raiden49** [comment]
1.catkin_find --without-underlays --libexec --share stanley_controller
2.cd src/stanley_controller
3.source ./build/devel/setup.bash
4.catkin_find --without-underlays --libexec --share stanley_controller
Check if there's only one package path in the results for steps 1 and 4.

**Comment by Raiden49** [comment]
I think I know where your issue lies! 
1.cd catkin_ws/src/stanley_controller
2.cmake -B build
3.cmake --build build
4.source ./build/devel/setup.bash
5roslaunch stanley_controller stanley_controller.launch

**Comment by Raiden49** [comment]
I tried it out, and if I don't compile 'stanley_controller' separately, I get the same error as you. So, it should solve your problem.

**Comment by YeanZeeon** [comment]
bravo, my friend! it works, thank you so much

**Comment by Raiden49** [comment]
My pleasure！
